== Thank You

* https://github.com/dmg46664[Daniel Gerson] -- Detailed notes on how to improve the labs
* https://twitter.com/adrianfcole[Adrian Cole] -- Tons of shared knowledge
* Attendees at Greach and Devoxx UK -- Tons of feedback
* https://zipkin.apache.org/[Apache Zipkin] -- Tons of inspiration from the docker compose

== How this Workshop is Setup

Labs are in a state where they will compile but not all are 100% correct. The answers are in the corresponding modules.

=== System Overview

[plantuml%interactive, plant-images/diagramoverdev, svg, height=350, width=400]
----
@startuml
  rectangle edge as "Edge"
  rectangle hub as "Hub"
	rectangle user as "User"
	rectangle report as "Report"
	database hubdb as "Hub\nDatabase"
	database userdb as "User\nDatabase"

  user -down-> userdb
  hub -down-> hubdb

  edge -down-> report
  edge -down-> hub
	edge -down-> user

	report -> hub
@enduml
----

=== Infra

All the shared infrastructure for observability is in this directory you can run it with docker-compose.

=== Requests

A handful of simple requests that can exercise the system easily are in this directory. Each service has a file.

=== Services

Each service is named for its role then a dash with it's framework. You only need to run one of each role.


=== Task List

There is a high level task list in each lab directory, that has a rough order on the things to explore. It also has general pointers of where to get started.

=== Gradle Build

The root gradle file isn't something you need to modify if you need to add dependencies you can do that in the gradle file for a given project in each lab.

Any libraries needed to solve the lab should be added to the project gradle file.

=== Wrap Up

We will do a wrap up discussion after each lab talking about more complex real world applications of the topics.


